const GEMINI_KEY_STORAGE = "resumeiq.geminiKey";
const GEMINI_MODEL = "gemini-3.6-flash";
const GEMINI_ENDPOINT =
  "https://generativelanguage.googleapis.com/v1beta/models/" +
  GEMINI_MODEL +
  ":generateContent";

function getStoredKey() {
  try {
    return localStorage.getItem(GEMINI_KEY_STORAGE) || "";
  } catch (e) {
    return "";
  }
}

function storeKey(key) {
  try {
    localStorage.setItem(GEMINI_KEY_STORAGE, key);
  } catch (e) {
    /* ignore */
  }
}

function buildPrompt(data) {
  return (
    "You are an expert resume coach and ATS specialist. A candidate scored " +
    data.score +
    "/100 matching their resume to a job description.\n\n" +
    "Missing keywords: " +
    (data.missing.length ? data.missing.join(", ") : "none") +
    "\n" +
    "Matched keywords: " +
    (data.matched.length ? data.matched.join(", ") : "none") +
    "\n\n" +
    "RESUME:\n" +
    data.resumeText.slice(0, 4000) +
    "\n\nJOB DESCRIPTION:\n" +
    data.jobText.slice(0, 4000) +
    "\n\nGive 5 concise, specific, actionable suggestions to raise the ATS score. " +
    "Each suggestion should be one short sentence. Return them as a plain numbered list, no preamble."
  );
}

function parseSuggestions(text) {
  return text
    .split("\n")
    .map(function (line) {
      return line.replace(/^\s*[\d.)\-*•]+\s*/, "").trim();
    })
    .filter(function (line) {
      return line.length > 0;
    });
}

function renderAISuggestions(items) {
  const list = document.getElementById("aiSuggestionsList");
  list.innerHTML = "";
  items.forEach(function (item) {
    const li = document.createElement("li");
    li.textContent = item;
    list.appendChild(li);
  });
}

function setAIStatus(message, isError) {
  const status = document.getElementById("aiStatus");
  status.textContent = message;
  status.classList.toggle("error", Boolean(isError));
}

async function requestGemini(apiKey, prompt) {
  const response = await fetch(
    GEMINI_ENDPOINT + "?key=" + encodeURIComponent(apiKey),
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
      }),
    },
  );

  if (!response.ok) {
    let detail = "";
    try {
      const errBody = await response.json();
      detail =
        errBody.error && errBody.error.message
          ? " - " + errBody.error.message
          : "";
    } catch (e) {
      /* ignore */
    }
    throw new Error("Gemini request failed (" + response.status + ")" + detail);
  }

  const body = await response.json();
  const text =
    body &&
    body.candidates &&
    body.candidates[0] &&
    body.candidates[0].content &&
    body.candidates[0].content.parts &&
    body.candidates[0].content.parts[0] &&
    body.candidates[0].content.parts[0].text;

  if (!text) throw new Error("Gemini returned no suggestions.");
  return text;
}

async function getAISuggestions() {
  const data = window.ResumeIQ;
  const btn = document.getElementById("aiBtn");

  if (!data) {
    setAIStatus("Run an analysis first.", true);
    return;
  }

  const apiKey = document.getElementById("geminiKey").value.trim();
  if (!apiKey) {
    setAIStatus("Enter your Gemini API key above to use AI suggestions.", true);
    return;
  }
  storeKey(apiKey);

  btn.disabled = true;
  btn.classList.add("loading");
  setAIStatus("Asking Gemini...", false);
  document.getElementById("aiSuggestionsList").innerHTML = "";

  try {
    const prompt = buildPrompt(data);
    const text = await requestGemini(apiKey, prompt);
    const suggestions = parseSuggestions(text);
    renderAISuggestions(suggestions);
    setAIStatus("Suggestions generated by " + GEMINI_MODEL + ".", false);
  } catch (err) {
    setAIStatus(
      err.message || "Something went wrong. Showing local tips instead.",
      true,
    );
  } finally {
    btn.disabled = false;
    btn.classList.remove("loading");
  }
}

function initGemini() {
  const keyInput = document.getElementById("geminiKey");
  if (keyInput) keyInput.value = getStoredKey();

  const btn = document.getElementById("aiBtn");
  if (btn) btn.addEventListener("click", getAISuggestions);

  document.addEventListener("resumeiq:analyzed", function () {
    document.getElementById("aiPanel").classList.remove("hidden");
  });
}

initGemini();
